### PR TITLE
Implementation of new units and restructure 

### PR DESCRIPTION
**Pull request by owinterbg**
The code in forked master works as expected for HEDv1.6.0-restruct.XML

### CODE REVIEW

**Comment by happy5214** [comment]
We had merged `master` into this branch before pushing this pull request, which broke compatibility with `unit_class_dev`. I recommend bulldozing the latter branch and replacing it with this one.

**Comment by VisLab** [comment]
Could you clarify what you are planning to do just so I understand.  The
master will now have unit-class validation with pluralize and unit
modifiers, but if the schema doesn't have unit modifiers it won't validate
using pluralize and unit modifiers, but just use the explicit unit classes?

**Comment by happy5214** [comment]
> Could you clarify what you are planning to do just so I understand. The master will now have unit-class validation with pluralize and unit modifiers, but if the schema doesn't have unit modifiers it won't validate using pluralize and unit modifiers, but just use the explicit unit classes?

I was proposing deleting the unit_class_dev branch and adding @owinterbg 's branch in its place. The URLs broke in the merge, and I submitted a PR to his repo to fix that. This branch is basically a clone of the JavaScript version as it currently exists. I haven't had time to implement the "fail fast" functionality you requested, so that's not included yet.

**Comment by VisLab** [comment]
Yes that sounds good.... please go ahead......

**Pull request closed without merging**
