### PR TITLE
add codespell: config, workflow and have typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
workflow would only detect when a new typo is introduced, it will not automagically inject its fix somehow.

more info on codespell: https://github.com/codespell-project/codespell

### CODE REVIEW

**Comment by VisLab** [comment]
@yarikoptic Thanks for the suggestion.  I am worried about the "fixing typo automagically" on the first round.  There are a number of items where a spell check change would be unfortunate.  I haven't use this before.  Is there a way to not do the automagically on the first round to see where the dust falls.  I'd like to put this on all our repos.

**Comment by yarikoptic** [comment]
Here is the adhoc script https://github.com/yarikoptic/improveit/blob/main/codespellit I used to add codespell here. I guess it could be organization wide workflow which would just check if project has codespell config to proceed, and then each repo would need similar pr fixing initial set of typos

**Comment by VisLab** [comment]
@yarikoptic unfortunately we're going to have to revert all of the codespell related commits as they changed the hed schema files which must not be changed regardless of typos.  I didn't notice it until I did the merges and then @ianca pointed it out.

This is going to take some work to do all of the proper excludes.

**Comment by yarikoptic** [comment]
It is easy to exclude files.  What files should I exclude?

**Comment by VisLab** [comment]
I need to revert all of the merges for all repos first since the HED schema
files were changed in all of them (I should have noticed -- sorry).

We will need to exclude all .xml files and all .mediawiki files except
those in a prerelease subdirectory.  Let me revert everything first, then
maybe you would be willing to do the modifications?  Thanks

**Comment by VisLab** [comment]
@yarikoptic - we fixed some of the exclusions and put your suggestions in another PR. Thx.

**Pull request closed without merging**
